version: '2'

volumes:
  nextcloud_data:
  db_data:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 3333:80
    links:
      - db
    volumes:
      - ./nextcloud_data:/var/www/html
    restart: always
